In [134]:
import numpy as np
from numpy import *


### 1) Creamos el array con las indicaciones


In [135]:
array_e = np.random.randint(3, 12, size=(5,7)) 

print(array_e)

[[11  4  7  7  5  4 10]
 [10  9  6  7  6 11  3]
 [ 4  7 10 10  5  3  9]
 [ 4  3  3  5 10  6 10]
 [ 7  6  3 11 10  4  5]]


a) Verificamos de que tipo de datos hay con funcion .dtype


In [136]:
print(array_e.dtype) 



int64


b) con la funcion .max descubrimos valor máximo


In [13]:
valor_maximo = np.max(array_e)
print(valor_maximo)

11


In [14]:
# c) 
valor_minimo=np.min(array_e)
print(valor_minimo)

3


d) con np.where(condicion) encontramos los indices de los elementos con dicha condición.
el formato que entrega esta funcion es de dos arrays, el primeto contiene la cordenada de las filas de cada elemento y el segundo indica las columnas.

In [101]:
cantidad_filas = array_e.shape[0] #Con función shape identificamos cantidad de filas
lis_valmin=[]
columna_i=[]                       #Creamos una matriz con dos columnas

for i in range(cantidad_filas): #Creamos ciclo for para pasar por todas las filas
    
    valor_minimo=np.min(array_e[i])   #Valor mínimo de cada fila
    indice=np.where(array_e[i] == valor_minimo)  #Cuál es el índice dentro de cada fila
    
    if len(indice[0]) == 1:              #Si se encuentra el número una vez, entonces agrega el único valor
        columna_i.append(indice[0][0])
        
    else:                             # Si se repite, entonces se crea una lista en el elemento de columna
        lis=[]
        for l in range(len(indice[0])):  #La cual indica las diferentes posiciones dentro de las columnas
            lis.append(indice[0][l])
        columna_i.append(lis)
            
    lis_valmin.append(valor_minimo)
    
#Respuesta por consola :)    

print('Los valores minimos de cada fila respectivamente son ')
for i in range(len(lis_valmin)):
    print('En fila '+ str(i) +' el elemento minimo es '+ str(lis_valmin[i]) +' y su indice en el array es ['+ str(i)+',' +str(columna_i[i])+'].')
    
    
    

Los valores minimos de cada fila respectivamente son 
En fila 0 el elemento minimo es 6 y su indice en el array es [0,[4, 6]].
En fila 1 el elemento minimo es 5 y su indice en el array es [1,2].
En fila 2 el elemento minimo es 4 y su indice en el array es [2,1].
En fila 3 el elemento minimo es 3 y su indice en el array es [3,0].
En fila 4 el elemento minimo es 5 y su indice en el array es [4,[2, 6]].


### 2.
Para crear un array de esas caracteristicas, ocupamos np.arange, donde indicamos el número por el cual debe partir y terminar, además del incremento que será 5

In [104]:

array=np.arange(4, 100, 5)
print(array)

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]


### 3.
Ocuparemos el mismo array anteriormente declarado y le aplicaremos la función reshape. Ésta utiliza los mismos datos con el mismo patrón y le cambia la dimensión a dicho array.

In [105]:
#arr_reshaped = arr.reshape(4, 3)
array_resh= array.reshape(4,5)
print(array_resh)

[[ 4  9 14 19 24]
 [29 34 39 44 49]
 [54 59 64 69 74]
 [79 84 89 94 99]]


### 4. 
Con el compando np.random hacemos un array con distintas dimensiones (en este caso 3) y con . normal, hacemos que la distribución sea normal (con escala de 1).

In [116]:
# crear un numpy array de 4 por 2 por 3 con valores normalmente distribuidos
arr = np.random.normal(loc=0, scale=1, size=(4, 2, 3))
print(arr)

[[[-0.72782345  1.94541742  1.54080643]
  [-0.66656893  0.27874864  0.26438218]]

 [[-0.66598538 -0.76301756 -1.05059152]
  [-1.25050292  0.16453793 -1.82031933]]

 [[ 0.0368164   0.47962179  1.29304339]
  [ 1.12823014 -1.272175    0.93791373]]

 [[ 0.20919702 -0.7098197   0.89612125]
  [ 0.07501978  1.05049023 -0.38242327]]]


### 5.
Ocupamos la función np.eye que nos crea una matriz identidad, le cual en el argumento le indicamos las dimensiones y el desfase vertical de -2

In [107]:
diag = np.eye(6, k=-2)
diag = diag.astype(int) #Le cambiamo el tipo de datos
print(diag)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


### 6.



In [114]:
array=np.arange(3,34,2)
#a) Seleccionas ultimos 4
ul_4 = array[-4:]
print(ul_4)


[27 29 31 33]


In [112]:
#b) Usamos % para seleccionar multiplos

mul_3 = array[np.where(array % 3 == 0)]

print(mul_3)

[ 3  9 15 21 27 33]


### 7. 

In [117]:
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])



72


In [118]:
# a) con el simbolo "-" podemos indicar el indice desde la perspectiva opuesta

valor=arr_2d[-1, -2]
print(valor)


In [120]:
# b) debido a que el subarray se encuentra entre las posiciones de fila 2,3 y 4, además de posición de columna
#3,4 y 5. damos las indicaciones de la siguiente manera

s_array=arr_2d[2:5, 3:6]
print(s_array)

[[76  3  3]
 [26 71 77]
 [38 54 72]]


In [122]:
#c) el siguiente array contempla las filas 1, 2 y 3 con todas las columnas.

s_array= arr_2d[1:4,:]
print(s_array)

[[87 51 13 75 78 46 53]
 [43 24 58 76  3  3 57]
 [84 86 75 26 71 77  7]]


### 8

In [125]:
arr=np.arange(1,50,3)
print(arr)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [ ]:
#a)
arr0=arr[(arr > 7) & (arr < 43)] #Ocupamos & (y lógico) que concatena dos condiciones
print(arr0)

In [127]:
#b) En este caso agregamos una nueva condición en donde indicamos que debe ser multiplos de 2 o par
arr0=arr[(arr > 11) & (arr < 45) & (arr % 2 == 0)]
print(arr0)

[16 22 28 34 40]


### 9

In [130]:
# Crear un 1D array uniformemente distribuido con 20 elementos
arr = np.random.uniform(size=20)
print(arr)
print('')
# Calcular la media
mean = np.mean(arr)
print("Media:", mean)

# Calcular la desviación estándar
std = np.std(arr)
print("Desviación estándar:", std)

# Calcular la mediana
median = np.median(arr)
print("Mediana:", median)

# Calcular la media de los valores en log
mean_log = np.mean(np.log(arr))
print("Media de los valores en log:", mean_log)



[0.27765031 0.80207361 0.49587817 0.75163606 0.84373216 0.67903527
 0.63575738 0.00737381 0.66949786 0.65733072 0.43313323 0.49967879
 0.22297705 0.66567917 0.55580311 0.29998656 0.52104675 0.01950172
 0.55392464 0.18818912]

Media: 0.48899427359695
Desviación estándar: 0.23975393064405798
Mediana: 0.537485697037986
Media de los valores en log: -1.0654563668237413


### 10

In [131]:
# a) ocupamos np.flip para invertir el arreglo y .astype para cambiar el formato de los datos
def imprimir_invertido(arr):
    arr_inv = np.flip(arr).astype(float)
    print(arr_inv)
ej=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

imprimir_invertido(ej)

[23. 21. 19. 17. 15. 13. 11.  9.  7.  5.  3.  1.]


In [132]:
# b) flatten lo que hace es llevar el array de cualquier dimension y lo transforma a una
def imprimir1D(arr):
    arr0 = arr.flatten()
    print(arr0)
    
ej=np.array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])

imprimir1D(ej)

[7 4 8 3 6 3 4 3 4 7 5 4]
